# Generated by Django 3.1.4 on 2020-12-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csandphysicsblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='Image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
