# Generated by Django 3.1.4 on 2020-12-28 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csandphysicsblog', '0003_auto_20201228_1823'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
    ]
