# Generated by Django 3.1.4 on 2020-12-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csandphysicsblog', '0004_auto_20201228_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
