# Generated by Django 3.1.4 on 2020-12-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csandphysicsblog', '0006_auto_20201228_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='Image',
        ),
        migrations.AddField(
            model_name='detail',
            name='Author_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='detail',
            name='Image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Added_by',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
