# Generated by Django 3.1.4 on 2020-12-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csandphysicsblog', '0008_auto_20201229_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='Author_pic',
            field=models.ImageField(blank=True, upload_to='blog_images'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Image',
            field=models.ImageField(blank=True, upload_to='blog_images'),
        ),
    ]
