# Generated by Django 3.1.4 on 2020-12-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csandphysicsblog', '0009_auto_20201229_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='Author_pic',
            field=models.ImageField(blank=True, upload_to='static/blog_images'),
        ),
    ]
