# Generated by Django 3.1.4 on 2020-12-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csandphysicsblog', '0011_auto_20201229_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Topic', models.CharField(max_length=100)),
                ('Message', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'Connect',
            },
        ),
    ]
