# Generated by Django 3.1.4 on 2021-03-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csandphysicsblog', '0012_connect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='Message',
            field=models.CharField(max_length=500),
        ),
    ]
