# Generated by Django 3.1.4 on 2021-03-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csandphysicsblog', '0013_auto_20210304_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='Message',
            field=models.TextField(max_length=500),
        ),
    ]
