# Generated by Django 3.1.4 on 2021-03-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csandphysicsblog', '0014_auto_20210305_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(default='', max_length=100)),
                ('Topic', models.CharField(default='', max_length=100)),
                ('Sub_Topic', models.CharField(default='', max_length=100)),
                ('Matter', models.CharField(default='', max_length=20000)),
            ],
        ),
    ]
