# Generated by Django 5.2.17 on 2026-09-12 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=80)),
                (
                    "headline",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Physics undergrad, writes about optics".',
                        max_length=140,
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=1000)),
                ("avatar", models.ImageField(blank=True, upload_to="avatars")),
                ("location", models.CharField(blank=True, max_length=80)),
                ("website", models.URLField(blank=True)),
                (
                    "github",
                    models.CharField(
                        blank=True, help_text="Username only.", max_length=60
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True, help_text="Handle without the @.", max_length=60
                    ),
                ),
                (
                    "linkedin",
                    models.CharField(
                        blank=True, help_text="Username only.", max_length=100
                    ),
                ),
                (
                    "can_write",
                    models.BooleanField(
                        default=False,
                        help_text="Lets this user write and publish posts from the dashboard.",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
