"""Regenerate static/css/code.css from Pygments styles.

Run after changing LIGHT_STYLE / DARK_STYLE:

    python manage.py make_code_css
"""

from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand
from pygments.formatters import HtmlFormatter

LIGHT_STYLE = "xcode"
DARK_STYLE = "github-dark"

# Pygments emits a few global rules we do not want: they would fight the design
# system's own background, line-height and gutter styling.
SKIP_PREFIXES = (
    "pre {",
    "td.linenos",
    "span.linenos",
    ".codehilite {",
    ".codehilite .hll",
)

CHROME = """/* =========================================================================
   Code blocks: chrome + Pygments token colours for both themes.
   Generated by `python manage.py make_code_css` — edit that command, not this.
   ========================================================================= */

.codehilite {
  position: relative;
  margin-block: 1.75em;
  border-radius: var(--radius);
  border: 1px solid var(--code-border);
  background: var(--code-bg);
  overflow: hidden;
  font-family: var(--font-mono);
}

.codehilite pre {
  margin: 0;
  padding: 1.1rem 1.2rem;
  overflow-x: auto;
  font-size: 0.855rem;
  line-height: 1.65;
  tab-size: 4;
  color: var(--code-fg);
}

.codehilite code {
  font-family: inherit;
  background: none;
  padding: 0;
  border: 0;
}

.code-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 0.75rem;
  padding: 0.45rem 0.5rem 0.45rem 0.9rem;
  border-bottom: 1px solid var(--code-border);
  background: var(--code-head-bg);
  font-family: var(--font-sans);
  font-size: 0.72rem;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--text-muted);
}

.code-copy {
  display: inline-flex;
  align-items: center;
  gap: 0.35rem;
  padding: 0.25rem 0.6rem;
  border-radius: var(--radius-pill);
  border: 1px solid var(--code-border);
  background: transparent;
  color: var(--text-muted);
  font-family: var(--font-sans);
  font-size: 0.7rem;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  cursor: pointer;
  transition: color 0.15s var(--ease), border-color 0.15s var(--ease);
}
.code-copy:hover { color: var(--accent); border-color: var(--accent); }
.code-copy.is-done { color: var(--success); border-color: var(--success); }

/* Inline code */
.prose :not(pre) > code,
.comment-body :not(pre) > code {
  font-family: var(--font-mono);
  font-size: 0.855em;
  padding: 0.15em 0.4em;
  border-radius: 5px;
  background: var(--bg-sunken);
  border: 1px solid var(--border);
  color: color-mix(in oklab, var(--accent) 75%, var(--text));
  word-break: break-word;
}

:root {
  --code-bg: #fbfcfe;
  --code-fg: #1f2328;
  --code-border: var(--border);
  --code-head-bg: #f1f4f8;
}

.dark-code-vars,
[data-theme="dark"] {
  --code-bg: #0f1217;
  --code-fg: #d9e0ea;
  --code-border: #242a33;
  --code-head-bg: #171b22;
}
"""


def token_rules(style: str, scope: str = "") -> str:
    css = HtmlFormatter(style=style, cssclass="codehilite").get_style_defs(".codehilite")
    lines = []
    for raw in css.splitlines():
        line = raw.strip()
        if not line or line.startswith("/*") or line.startswith(SKIP_PREFIXES):
            continue
        lines.append(f"{scope} {line}" if scope else line)
    return "\n".join(lines)


class Command(BaseCommand):
    help = "Regenerate static/css/code.css with Pygments token colours."

    def handle(self, *args, **options):
        target = Path(settings.BASE_DIR) / "static" / "css" / "code.css"
        parts = [
            CHROME,
            f"\n/* Light tokens — Pygments “{LIGHT_STYLE}” */",
            token_rules(LIGHT_STYLE),
            f"\n/* Dark tokens — Pygments “{DARK_STYLE}” */",
            token_rules(DARK_STYLE, '[data-theme="dark"]'),
            "\n@media (prefers-color-scheme: dark) {",
            '  :root:not([data-theme="light"]) {',
            "    --code-bg: #0f1217;",
            "    --code-fg: #d9e0ea;",
            "    --code-border: #242a33;",
            "    --code-head-bg: #171b22;",
            "  }",
            token_rules(DARK_STYLE, '  :root:not([data-theme="light"])'),
            "}",
            "",
        ]
        target.write_text("\n".join(parts))
        self.stdout.write(self.style.SUCCESS(f"Wrote {target.relative_to(settings.BASE_DIR)}"))
